Build: Use pkg-config to link to xnvme
OpenMPDK/FlexAlloc pull request #8
Opened 2022-01-24 16:01 UTC by Joelgranados

Signed-off-by: Joel Granados <j.granados@samsung.com>

2022-01-31 12:48 UTC, Joelgranados commented
@jwdevantier @nmtadam. This is no longer WIP as xNVMe is v28 is out. I suggest we push this after the daemon goes in as it applies cleanly on top.

2022-01-31 20:33 UTC, nmtadam requested changes
Can we squash this down to one commit? This also does not cleanly apply onto master. I tried just adding the changes but the tests aren not correctly running for me. I got a fla_daemon_open as an undefined symbol.

2022-02-02 13:57 UTC, Joelgranados commented
> squashing down and committing. @nmtadam 

Of course, I was just planning to do it when we do the merge. So select squash and merge instead of rebase and merge.

2022-02-02 14:26 UTC, Joelgranados commented
@nmtadam : just did the squash when I did the rebase

2022-02-07 17:25 UTC, nmtadam commented
This breaks the python bindings for me.

```
tests/test_libflexalloc.py FFFFF                                                                                                                                                                   [ 76%]
tests/test_mkfs.py FF                                                                                                                                                                              [ 84%]
tests/test_pool_root.py FF                                                                                                                                                                         [ 92%]
tests/test_sync.py FF 
```

2022-02-08 13:16 UTC, Joelgranados commented
@nmtadam : I do not see the failure. are you sure you are in `e8a1897`.
It might be that you are in a previous version of the PR.

2022-02-08 14:14 UTC, jwdevantier commented on meson.build
> +xnvme_deps = dependency('libxnvme', version : '>=0.0.27' )
I think for now it's OK to move fast along-side xNVMe, but Adam has a valid point. Down the road, we should figure out if we can avoid requiring everyone to use the very, very latest xNVMe (and especially kernel, if that applies, as it's a mess to upgrade on production systems).

2022-02-08 17:26 UTC, merged